malcolmstill/zware

- .github/workflows/test.yaml
- README.md
- examples/fib/src/fib.zig
- src/common.zig
- src/function.zig
- src/instance.zig
- src/instruction.zig
- src/interpreter.zig
- src/module.zig
- src/store.zig
- test/src/testrunner.zig
Moves `interpret` into `invoke`
- In preparation of trying to force an optimisation to give us a jump (and hence branch prediction) for each op rather than a single jump, this moves `interpret` into `invoke`
- When making the change I realised that a) the GitHub Action was failing because the nightly I was pointing at disappeared b) on updating the version there are some changes that broke `foxwren`, namely (and I'm guessing here without having looked into it) where `ArrayList` reallocates, the old data is overwritten with `0xAA` whereas I was using the fact that I was an arena allocator so that so any "invalid" pointer into the old chunks would continue to exist. With this no longer being true due to the overwriting I had to remove that assumption.
That affected:
- `parsed_code`
- …
> refactor: move interpret into invoke

- .dockerignore
- .github/workflows/test.yaml
- Dockerfile
- README.md
Running the testsuite requires a particular version of `wabt` that can be awkward to install. If we use a docker image instead running the testsuite will be easier for people (assuming they have docker installed)
> feat: test using docker

- src/common.zig
- src/function.zig
- src/instance.zig
- src/instruction.zig
- src/interpreter.zig
- src/module.zig
- src/validator.zig
- Moves operand stack overflow checks to granularity of function.
- Operand stack overflow check performed at function call
- Instructions that previously increased operand stack usage (and so performed an overflow check) no longer perform overflow checks
- Remove `ip_end`
```
fib(39) = 63245986
Performance counter stats for './fib':
12,042.78 msec task-clock:u              #    0.993 CPUs utilized          
0      context-switches:u        #    0.000 /sec                   
0      cpu-migrations:u          #    0.000 /sec                   
22      page-faults:u             #    1.827 /sec                   
37,726,320,071      cycles:u                  #    3.133 GHz                      (28.57%)
10,444,544,015      stalled-cycles-frontend:u #   27.69% frontend cycles idle     (28.58%) …
```
> Operand stack size check on function call instead of instruction

- src/interpreter.zig
This is the one I've been looking forward to!
The stage 2 compiler fixes some bugs that prevent using `.always_tail` with a return value. As a workaround I had been doing the error returns by passing a pointer to an error as an argument to the recursive functions.
This PR moves the `WasmError` into its rightly place: the function return value. The added benefit is we get to use `try` again!
E.g.
```zig
fn call_indirect(self: *Interpreter, ip: usize, code: []Instruction, err: *?WasmError) void {
const call_indirect_instruction = code[ip].call_indirect;
var module = self.inst.module;
const op_func_type_index = call_indirect_instruction.@"type";
const table_index = call_indirect_instruction.table;
// Read lookup index from stack
const lookup_index = self.popOperand(u32);
const table = …
```
> Move WasmError from argument to return type

- test/src/testrunner.zig
- Only do a single `module.decode` and single capture of `err`
> Rearrange testrunner assert_malformed

- src/vm.zig
Previously the misc instructions were dispatched in a large switch statement. This moves to the same model as all other instructions, i.e. they are now `always_tail`'d with via a `misc_lookup` table
> Dispatch misc instructions in the same way as the other instructions

- src/parser.zig
- src/validator.zig
Remove another place where we need to add opcodes + have the compiler help us more.
Note: I tried to get rid of the `var rr: Rr = undefined` by using `break` from a block, but that doesn't seem to be working (will try again in the future).
> Clean up validation

- src/instance/vm.zig
- src/store/memory.zig
I dislike having the pages explicit in the implementation of memory, i.e I dislike `ArrayList([PAGE_SIZE]u8)` and am changing it to a flat `ArrayList(u8)`
> Flatten memory

- src/instance/vm.zig
- src/store/memory.zig
The previous implementations of `memory.fill` and `memory.copy` were correct in a semantic sense but not in a performant sense (the reason for their introduction into the WebAssembly spec).
This removes individual byte writes (with a check on each byte written...i.e. slow) with trusting the bounds check in the virtual instruction handler.
- I think we should just push the bounds check into `Memory`
- If we do this can we unify `Memory.copy` and `Memory.uncheckedCopy`
> Fast memory.fill and memory.copy

- .github/workflows/test.yaml
- .gitignore
- README.md
- build.zig
- examples/fib/build.zig
- src/instance.zig
- src/instance/vm.zig
- src/module.zig
- src/module/parser.zig
- src/module/validator.zig
- src/store/function.zig
- src/store/memory.zig
- test/fuzzer/build.zig
- test/fuzzer/src/fuzzer.zig
- test/interface/build.zig
- test/interface/src/interface.zig
- test/parsecheck/build.zig
- test/parsecheck/src/parsecheck.zig
- test/run-generated.sh
- test/testrunner/build.zig
- test/testrunner/src/testrunner.zig
Not ready to merge. After these changes, the modules can individually build with 0.11.0-dev.3132+465272921 but the testrunner build command fails:
```
$ zig build --build-file test/testrunner/build.zig --prefix ./
zig build-exe testrunner Debug native: error: warning: FileNotFound: test/testrunner/src/main.zig
error: FileNotFound
```
Yours truly looked into it and found that it is a build system bug. Here's the fix: https://github.com/ziglang/zig/pull/15717 Hopefully that can get into the release. Shake and bake!
> fixes for compatibility with zig 0.11.0

- src/store.zig
- test/testrunner/src/testrunner.zig
Fixes part of https://github.com/malcolmstill/zware/issues/185. Adds a `addHostFunction` to the `Store` that simplifies loading a host function.
> Add addHostFunction as suggested by @TUSF

- .github/workflows/test.yaml
- test/generate_interface/README.md
- test/generate_interface/build.zig
- test/generate_interface/src/main.zig
- test/interface/README.md
To help write host functions for known wasm binaries, adds a `generate_interface` binary that given a `.wasm` binary will generate host function stubs and a `initHostFunctions` function.
E.g. if I take the `.wasm` from https://silentspacemarine.com/ the binary generates:
```zig
const std = @import("std");
const zware = @import("zware");
pub fn initHostFunctions(module: []const u8, store: *zware.Store) !void {
try store.addHostFunction(module, "exit", exit, [_]ValType{.I32, }, [_]ValType{});
try store.addHostFunction(module, "emscripten_cancel_main_loop", emscripten_cancel_main_loop, [_]ValType{}, [_]ValType{});
try store.addHostFunction(module, "emscripten_force_exit", emscripten_force_exit, [_]ValType{.I32, }, [_]ValType{});
try store.addHostFunction(module, "time", time, …
```
> Add a generate_interface program 

- test/generate_interface/src/generate_interface.zig
https://github.com/malcolmstill/zware/pull/197 generated stubs for host functions and provided a function for loading those functions into the runtime. What this PR is wraps calls to `instance.invoke` for all the functions _exported_ by the `.wasm` binary.
For example, the https://silentspacemarine.com/ `.wasm` gives:
```zig
pub fn __wasm_call_ctors(instance: *zware.Instance) !void {
var in = [_]u64{};
var out = [_]u64{};
try instance.invoke("__wasm_call_ctors", in[0..], out[0..], .{});
}
pub fn main(instance: *zware.Instance, param0: i32, param1: i32) !i32 {
var in = [_]u64{@bitCast(@as(i64, param0)), @bitCast(@as(i64, param1))};
var out = [_]u64{0};
try instance.invoke("main", in[0..], out[0..], .{});
return @bitCast(@as(u32, @truncate(out[0])));
}
pub fn malloc(instance: …
```
> Generate wrappers for invoking wasm functions

- tools/zware-gen/README.md
- tools/zware-gen/src/zware_gen.zig
Wrap the calls to `.wasm` module functions in a struct that carries its instance
E.g. for `fib.wasm` we get:
```zig
pub const Api = struct {
instance: *zware.Instance,
const Self = @This();
pub fn init(instance: *zware.Instance) Self {
return .{ .instance = instance };
}
pub fn fib(self: *Self, param0: i32) !i32 {
var in = [_]u64{@bitCast(@as(i64, param0))};
var out = [_]u64{0};
try self.instance.invoke("fib", in[0..], out[0..], .{});
return @bitCast(@as(u32, @truncate(out[0])));
}
};
```
> zware-gen: Improve interface

- README.md
- src/instance.zig
- src/instance/vm.zig
- src/main.zig
- src/wasi/wasi.zig
- tools/zware-gen/src/zware_gen.zig
- Modifies `zware-gen` so no function stubs are created for wasi functions (module `wasi_snapshot_preview1`)
- Implements enough wasi to run doom!
- Luckily, as part of ditching the C++ implementation of the zig compiler, Andrew / Jacob have done the hard work and showed how to implement a bunch of these functions in https://github.com/andrewrk/zig-wasi 
- Adds an api (via `Instance`) for adding preopens and forwarding on args
- Whilst the interface is on `Instance`, access within the wasi functions is via `VirtualMachine` directly (because remember `vm.inst` (potentially) changes to different `Instance`s during execution...the non-invoking `Instance`s will not have preopens / args
https://github.com/malcolmstill/zware/assets/2567177/c9acdcb2-69e7-495f-b3f1-89cf6b807a43
- Need to …
> wasi: define wasi implementations + zware-gen uses these definitions

- src/instance/vm.zig
A simple fix to avoid a now deprecated variable in std.math (replaced with a function). Fix works on both 0.11.0 and master at the time of writing.
> Fix not compiling on 0.12 dev version

- build.zig
Updated code in build.zig to use std.Build.path instead of constructing LazyPath's directly.  This should make build.zig compatible with both 0.12.0 and 0.13.0.
> use std.Build.path for 0.13.0 compatibility

- .gitignore
- src/module.zig
- src/module/parser.zig
This change moves the state (fixed buffer stream) and methods (decode/read) around decoding a module into a separate struct `Decoder` so they can be discarded after the module is decoded.
Along with this change, I also fixed a few more things I noticed along the way:
* removed version field from Module (unused)
* combined common code between min/max limit cases
* rename `module` field to `wasm_bin` on Module struct to distinguish the wasm binary buffer from the higher level module object
* fixed `readSlice` so it doesn't call skipBytes which unnecessarily
copies the entire slice and throws it away
* add .zig-cache to .gitignore for zig 0.13.0
> separate module decoding state/methods into their own struct

- src/module.zig
- src/module/parser.zig
There was a few mismatches where readULEB was being called with signed types. I fixed those and collapsed the readILEB/readULEB into one readLEB function that just uses the signedness of the native type to determine which underlying function to use.
> fix a few unsigned/signed readI/ULEB mismatches

- build.zig
- src/error.zig
- src/instance.zig
- src/instance/vm.zig
- src/main.zig
- src/module.zig
- src/store.zig
- src/store/function.zig
- test/testrunner/src/testrunner.zig
- tools/zware-run/main.zig
An initial version of a command-line program that can take a WASM binary on the command line and a function name and execute it.
It will find missing imports and populate them with "stubs". The stub will log the call and then populate the results with "zeroed" values. An enhancement could be to take multiple files on the command line and link them together before execution.
A few examples of binaries I could use with this was:
- binaries from the test suite
- WASM4 binaries
- the Zig wasm executable
Of the ones I tested this seems like a viable strategy to quickly run the binaries from the test suite.  The WASM4/Zig binaries would usually just call a function or two and then hit an assert because of the "zeroed" results that are produced by the stubs.
> add zware-run to run wasm binaries from the command-line
